### DISCUSSION TITLE
Global variables as context

### DISCUSSION THREAD

**Discussion by philtweir** [flaxandteal/dewret#20] [Ideas]
_From discussion_

The current approach to define workflow inputs is to use global variables
as shown in the Parameters help section - one may intuitively expect to define workflow input by
defining global variables and passing them as arguments to tasks, e.g.

```python
import sys
import yaml
from dewret.tasks import task, run
from dewret.renderers.cwl import render
some_number = 3
@task()
def increment(num: int) -> int:
  return num + 1
result = increment(num=some_number)
workflow = run(result)
cwl = render(workflow)
yaml.dump(cwl, sys.stdout, indent=2)

```

The produced output reads

```yaml
class: Workflow
cwlVersion: 1.2
inputs: {}
outputs:
    out:
        label: out
        outputSource: increment-012ef3b3ffb9d15c3f2837aa4bb20a8d/out
        type: int
steps:
    increment-012ef3b3ffb9d15c3f2837aa4bb20a8d:
        in:
            num:
                default: 3
        out:
        - out
        run: increment
```

Currently the only intended way of defining workflow input is using global
variables.

### Proposal

- can we remove context aware functions because they are violating the
encapsulation and the very idea behind a function, i.e. that a function should be a stateless and entirely
encapsulated entity whose result should only depend on the explicit input
