### DISCUSSION TITLE
Parameters in dewret

### DISCUSSION THREAD

**Discussion by thomas-lemma** [flaxandteal/dewret#80] [General]
## What?

The handling of input arguments in tasks/workflows is confusing and non-intuitive for me. It would be nice to document the idea and the concept in more detail and, if possible, simplify the handling of input arguments and parameters.

## Detailed explanation and thoughts

I will try to clarify my misunderstanding regarding the topic in a few examples below. As a preliminary note, the following explanation is my understanding of the concepts and might be naive or wrong; I apologize in advance.

1. I start with the following simple workflow

    ```python
    import yaml
    
    from dewret.renderers.cwl import render
    from dewret.tasks import task, construct, workflow
    
    
    @task()
    def concat_strings(str1: str, str2: str) -> str:
        return str1 + str2
    
    
    @workflow()
    def create_greeting_in_all_caps(prefix: str, name: str) -> str:
        prefix_cap = prefix.__default__.capitalize()
        name_cap = name.__default__.capitalize()
        return concat_strings(str1=prefix_cap, str2=name_cap)
    
    
    
    result = create_greeting_in_all_caps(prefix="Hello to ", name="John")
    workflow = construct(result, simplify_ids=True)
    cwl = render(workflow)
    ``` 

    The render executes successfully and as far as I can tell, the result looks fine. The first point I want to raise is the shadowing of the initial input arguments prefix and name. To my understanding, they are shadowed by internal `dewret.workflow.ParameterReference` objects. Accessing the argument value needs to be done using the magic `__default__` property. Multiple thoughts/questions with respect to that:

    - As a naive user, this replacement of an input argument of a primitive type `str` by a complex object is surprising/non-intuitive. Could we instead create a `ParameterReference` to the input arguments with a different name (to avoid shadowing)? I.e., to allow altering and simplifying the above example to:

      ```python
      @workflow()
      def create_greeting_in_all_caps(prefix: str, name: str) -> str:
          prefix_cap = prefix.capitalize()
          name_cap = name.capitalize()
          return concat_strings(str1=prefix_cap, str2=name_cap)
      ```
    If this is not possible for very fundamental reasons, then at least two points:

    - The concept of shadowing and the handling of `dewret` `Parameter` and `ParameterReference` objects needs to be introduced and documented.
    - Maybe provide a more expressive property to access the value, for example, just `value`? Using `__default__` is not only bulky, but as a magic method, it signals a "non-basic" workflow that relies on internals to me. 

2. Extending the above example by simply reusing the `create_greeting_in_all_caps` workflow
    ```python
    @workflow()
    def greeting_workflow(name: str) -> str:
        prefix = "Hello to "
        return create_greeting_in_all_caps(prefix=prefix, name=name)
    
    
    result = greeting_workflow(name="John")
    workflow = construct(result, simplify_ids=True)
    cwl = render(workflow)
    ```
    leads to an error
    
    ```bash
    dewret.tasks.TaskException: 'str' object has no attribute '__default__'
    Task create_greeting_in_all_caps declared in <module> at workflow_mod_buggy.py:21
    @workflow()
    ```
    To fix this one must either: 
    - Alter the initial workflow `create_greeting_in_all_caps` to 
      ```python
      @workflow()
      def create_greeting_in_all_caps(prefix: str, name: str) -> str:
          prefix_cap = prefix.capitalize()
          name_cap = name.__default__.capitalize()
          return concat_strings(str1=prefix_cap, str2=name_cap)
      ```
     This is bad from my point of view for two reasons: i) It requires modifying an existing workflow, which impacts the former use case (example 1), and ii) there is inhomogeneous handling of arguments prefix and name.
    
    or
    - Pass the prefix as `Parameter`:
        ```python
        @workflow()
        def greeting_workflow(name: str) -> str:
            prefix = Parameter("prefix","Hello to ")
            return create_greeting_in_all_caps(prefix=prefix, name=name)
        ```
      This is bad from my point of view because: i) One needs to pass a complex object instead of the primitive type specified in the argument list, and ii) this is inconsistent with the case where I want to render the workflow which just uses primitive types, see example 1, i.e.,
      ```python
      result = create_greeting_in_all_caps(prefix="Hello to ", name="John")
      workflow = construct(result, simplify_ids=True)
      cwl = render(workflow)
      ```

## Summary

To me, the handling of input arguments to tasks and workflows is surprising. It would be nice to simplify the concept, avoiding the need for the user to deal with `dewret` `Parameter` and `ParameterReference` objects for basic use cases at all (avoid shadowing etc.), if possible. If this is not possible, it would at least be nice to make the handling consistent across the different use cases (compare examples 1 and 2). In any case, it would be important to document the concept and educate users about it.

**Comment by edufnt** [comment]
I think this discussion is crucial in that it highlights a lot of the subtleties of using dewret,  as well some possible workarounds, and some possible changes. I don't understand the implications of those changes fully, to say whether they are warranted.

However, in my current understanding there is a logic to the current implementation, by default dewret assumes all logic will happen a workflow run time, inputs are just default parameters, and guards against calling methods at render time.

So this works, because dewret understands that capitalization happens at run time:

```py
from dewret.renderers.cwl import render
from dewret.tasks import task, construct, workflow

@task()
def concat_strings(str1: str, str2: str) -> str:
    return str1 + str2

@task()
def cap(arg: str) -> str:
    return arg.capitalize()

@workflow()
def create_greeting_in_all_caps(prefix: str, name: str) -> str:
    prefix_cap = cap(arg=prefix)
    name_cap = cap(arg=name)
    return concat_strings(str1=prefix_cap, str2=name_cap)

result = create_greeting_in_all_caps(prefix="Hello to ", name="John")
workflow = construct(result, simplify_ids=True)
cwl = render(workflow)
cwl
```

which is reflected in its output:

```yaml
{
  "__root__":
    {
      "cwlVersion": 1.2,
      "class": "Workflow",
      "inputs":
        {
          "create_greeting_in_all_caps-1-name":
            { "label": "name", "type": "string", "default": "John" },
          "create_greeting_in_all_caps-1-prefix":
            { "label": "prefix", "type": "string", "default": "Hello to " },
        },
      "outputs":
        {
          "out":
            {
              "label": "out",
              "type": "string",
              "outputSource": "create_greeting_in_all_caps-1/out",
            },
        },
      "steps":
        {
          "create_greeting_in_all_caps-1":
            {
              "run": "create_greeting_in_all_caps",
              "in":
                {
                  "name": { "source": "create_greeting_in_all_caps-1-name" },
                  "prefix":
                    { "source": "create_greeting_in_all_caps-1-prefix" },
                },
              "out": ["out"],
            },
        },
    },
  "create_greeting_in_all_caps-1":
    {
      "cwlVersion": 1.2,
      "class": "Workflow",
      "inputs":
        {
          "name": { "label": "name", "type": "string", "default": "John" },
          "prefix":
            { "label": "prefix", "type": "string", "default": "Hello to " },
        },
      "outputs":
        {
          "out":
            {
              "label": "out",
              "type": "string",
              "outputSource": "concat_strings-1-1/out",
            },
        },
      "steps":
        {
          "cap-1-1":
            {
              "run": "cap",
              "in": { "arg": { "source": "name" } },
              "out": ["out"],
            },
          "cap-1-2":
            {
              "run": "cap",
              "in": { "arg": { "source": "prefix" } },
              "out": ["out"],
            },
          "concat_strings-1-1":
            {
              "run": "concat_strings",
              "in":
                {
                  "str1": { "source": "cap-1-2/out" },
                  "str2": { "source": "cap-1-1/out" },
                },
              "out": ["out"],
            },
        },
    },
}

```
The other option is to specify functions parameters to be render time parameters:

````py
from dewret.renderers.cwl import render
from dewret.tasks import task, construct, workflow
from dewret.annotations import AtRender

@task()
def concat_strings(str1: str, str2: str) -> str:
    return str1 + str2

@workflow()
def create_greeting_in_all_caps(prefix: AtRender[str], name: AtRender[str]) -> str:
    prefix_cap = prefix.capitalize()
    name_cap = name.capitalize()
    return concat_strings(str1=prefix_cap, str2=name_cap)

result = create_greeting_in_all_caps(prefix="Hello to ", name="John")
workflow = construct(result, simplify_ids=True)
cwl = render(workflow)
cwl
````
I would expect for the capitalization step to be done at render time and cut out from the rendered output, but it seems it is skipped altogether, I think this is probably a bug:

```yaml
{
  "__root__":
    {
      "cwlVersion": 1.2,
      "class": "Workflow",
      "inputs": {},
      "outputs":
        {
          "out":
            {
              "label": "out",
              "type": "string",
              "outputSource": "create_greeting_in_all_caps-1/out",
            },
        },
      "steps":
        {
          "create_greeting_in_all_caps-1":
            {
              "run": "create_greeting_in_all_caps",
              "in":
                {
                  "prefix": { "default": "Hello to " },
                  "name": { "default": "John" },
                },
              "out": ["out"],
            },
        },
    },
  "create_greeting_in_all_caps-1":
    {
      "cwlVersion": 1.2,
      "class": "Workflow",
      "inputs": {},
      "outputs":
        {
          "out":
            {
              "label": "out",
              "type": "string",
              "outputSource": "concat_strings-1-1/out",
            },
        },
      "steps":
        {
          "concat_strings-1-1":
            {
              "run": "concat_strings",
              "in":
                {
                  "str1": { "default": "Hello to " },
                  "str2": { "default": "John" },
                },
              "out": ["out"],
            },
        },
    },
}

```

Moreover, I still think that the place where one has to apply `AtRender` is counterituitive and requires trial and error, annotating the input variables and passing them to `create_greeting_in_all_caps(prefix: str, name: str) -> str` doesn't work:

```py
 rt_prefix: AtRender[str] = "Hello to "
 rt_name: AtRender[str] = "John"
 
```
