### ISSUE TITLE
Summarize "construct args and renderer args" in single render config

### ISSUE THREAD

**Issue by gitkief** [flaxandteal/dewret#74]
## What?

Following the [docs](https://flaxandteal.github.io/dewret/docs/quickstart/#usage) the `render` function is the default entrypoint to dewret. It takes two config arguments for `construct` and `renderer` specific. 

https://github.com/flaxandteal/dewret/blob/68ef970dcd8104c7369d09305cfacd14d4b31e0b/src/dewret/__main__.py#L60-L62

Helping people understand the internals can be valuable for advanced use cases, but for simpler ones, this already exposes the internal structure unnecessarily (to my opinion).  So the concern of this issues is if we can consolidate the configurations into a single render config.

## Sketch

Following the doc's [Usage example](https://flaxandteal.github.io/dewret/docs/quickstart/#programmatic-usage) this might read
```bash
python -m dewret --pretty workflow.py increment num:3  --render-config <from render_config.yaml>
```
with a unified config yaml which could follow some schema
```yaml
# render_config.yaml

# Former construct specifc config.. from the users point of view I would rather call it "basic render settings" 
simplify_ids: true 
# Additional render specific config, here CWL, extending the "basic render settings"
factories_as_params: true
```

**Note**: This relate also to the #70 at the signature of this function.
